### ISSUE TITLE
There has a bug report

### ISSUE THREAD

**Issue by mingtop** [ehodneland/cellsegm#2]
Undefined function 'centergrid' for input arguments of type 'double'.

Error in gaussian (line 29)
[x,minx,maxx] = centergrid(ceil(dim),ceil(h));

**Comment by ehodneland** [comment]
Hi Yan Ming,

Thank you for notifying me. I updated gaussian.m and forgot the 
subroutine. It should now be in place.
Please email me if anything is not working

Best, Erlend
