### ISSUE TITLE
Examples not working

### ISSUE THREAD

**Issue by DarkCellAD** [ehodneland/cellsegm#3]
In all the latest ~10 commits I cannot seem to get the examples to work. (I only tried 3D examples but none worked) They exit with various errors from missing functions over index mismatches to missing input arguments. Hence I cannot really try out the code to get it to work for me.
I'm working on Matlab 2015b.
For the latest commit:
Example "surf stain_3D"

Index exceeds matrix dimensions.

Error in gaussian (line 59)
    g = (1/n)*exp(-(1/2)*(sigmainv(1,1)*x{1}.^2 + sigmainv(2,2)*x{2}.^2 +
    sigmainv(3,3)*x{3}.^2));

Error in cellsegm.ridgeenhhessian (line 68)
g1 = gaussian(dim,prm.stdev);

Error in cellsegm.segmsurf (line 323)
    imsegm = cellsegm.ridgeenhhessian(imsegm,prm.h);

Error in surfstain_3D (line 41)
    cellsegm.segmsurf(imsegm,20,100,'prm',prm);

Example "surfstain_and_nucleus_3D"

Not enough input arguments.

Error in ball (line 20)
        if length(size) == 1,

Error in cellsegm.segmct>segmthrs (line 624)
    load ball1;se = getball(ball,1,1);

Error in cellsegm.segmct (line 213)
    [cellbw] = segmthrs(im,prmin,conn);

Error in cellsegm.getminima>nucleus (line 440)
[minimahere,wat] =
cellsegm.segmct(imhere,0.1*prm.minvolfull/1000,prm.maxvolfull/1000,'prm',prmin);

Error in cellsegm.getminima (line 219)
    minimacell = nucleus(imnucl,prmin);

Error in cellsegm.segmsurf (line 355)
        [minima,minimacell,prmout] =
        cellsegm.getminima(imsegm,minimacell,prmin,imnucl);

Error in surfstain_and_nucleus_3D (line 47)
    cellsegm.segmsurf(imsegm,3,100,'imnucleus',imnucl,'prm',prm);

Example "tissue_3D"

Unable to load ../data/tissue/stack3
Unable to read file '../data/tissue/stack3'. No such file or directory.
Could not load ../data/tissue/stack3, continuing
Unable to load ../data/tissue/stack4
Unable to read file '../data/tissue/stack4'. No such file or directory.
Could not load ../data/tissue/stack4, continuing

**Comment by ehodneland** [comment]
Hi,

thanks for the message. I will fix it within two hours.

Best, Erlend

**Comment by ehodneland** [comment]
Hi,

if you pull the latest version the bug should be fixed. Regarding the 
last error message
Unable to load ../data/tissue/stack3
Unable to read file '../data/tissue/stack3'. No such file or directory.
Could not load ../data/tissue/stack3, continuing
Unable to load ../data/tissue/stack4
Unable to read file '../data/tissue/stack4'. No such file or directory.
Could not load ../data/tissue/stack4, continuing

make sure that you have downloaded the given data as well, in 
../data/tissue/ (provided you are running the examples from the example 
folder)

Best regards

Erlend Hodneland
